carpool_news/carpool_news/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'carpool_news.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('rides.urls', namespace='rides')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', include(admin.site.urls)),
)

carpool_news/rides/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'rides.views.index', name='index'),
)

carpool_news/users/urls.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^login$', 'users.views.login', name='login'),
    url(r'^logout$', 'users.views.logout', name='logout'),
    url(r'^register$', 'users.views.register', name='register'),
    url(
        r'^routes$',
        'users.views.list_user_routes',
        name='list_user_routes'),
    url(
        r'^delete_user_route/(?P<id>\d+)$',
        'users.views.delete_user_route',
        name='delete_user_route'),
    url(
        r'^create_user_route$',
        'users.views.create_user_route',
        name='create_user_route')
)

carpool_news/templates/base.html
<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Carpool News</title>

        <!-- Bootstrap CSS -->
        <!-- Flatly theme from bootswatch -->
        {% load static %}

        <!-- django-bootstrap3 -->
        {% load bootstrap3 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.2.0/flatly/bootstrap.min.css" rel="stylesheet">

        <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <a class="navbar-brand">Carpool News</a>
            <ul class="nav navbar-nav navbar-left">
                <li class="{% block navbar-class-index %}{% endblock %}">
                    <a href="{% url 'rides:index' %}">
                        Skelbimai
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="{% block navbar-class-user %}{% endblock %}">
                    <a href="{% url 'users:list_user_routes' %}">
                        {{ user.username }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'users:logout' %}">
                        Atsijungti
                    </a>
                </li>
                {% else %}
                <li class="{% block navbar-class-register %}{% endblock %}">
                    <a href="{% url 'users:register' %}">
                        Registruotis
                    </a>
                </li>
                <li class="{% block navbar-class-login %}{% endblock %}">
                    <a href="{% url 'users:login' %}">
                        Prisijungti
                    </a>
                </li>
                {% endif %}
                <li style="width: 15px;"></li>
            </ul>
        </nav>

        <div class="container">
            {% block content %}{% endblock %}
        </div>

        <footer>
            <div class="container">
                <hr>
                <p style="float: right;">
                    Tomas Raila © 2014
                </p>
            </div>
        </footer>

        <!-- jQuery -->
        <script src="//code.jquery.com/jquery.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <!-- Bootstrap pagination plugin -->
        <script type="text/javascript" src='{% static 'js/jquery.bootpag.min.js' %}'></script>

        <script type="text/javascript">
            // Change search field labels according to
            // selected ad type (looking for a ride or offering one)
            $(document).ready(function() {
                $('#is-looking-for-true').click(function() {
                    $('#label-from').text("Važiuoja iš:");
                    $('#label-to').text("Važiuoja į:");
                });
                $('#is-looking-for-false').click(function() {
                    $('#label-from').text("Važiuoju iš:");
                    $('#label-to').text("Važiuoju į:");
                });
            });

            // Set up pagination
            // Variables from server side
            var totalPages = {{ ride_pages }};
            var itemsPerPage = {{ rides_per_page }};

            function showPage(num) {
                // Pages are numbered from 1
                var pageIdx = num - 1;
                var showIdxStart = pageIdx * itemsPerPage;
                var showIdxEnd = (pageIdx + 1) * itemsPerPage - 1;
                $('#ride-list li.list-group-item').each(function(idx) {
                    if (idx >= showIdxStart && idx <= showIdxEnd) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                });
            };

            // Don't do pagination if there's just one page
            if (totalPages > 1) {
                // Enable 'jquery-bootpag' plugin
                $('#pagination').bootpag({
                    total: {{ ride_pages }},
                }).on("page", function(event, num) {
                    showPage(num);
                });
            }

            // Display first page on page load
            showPage(1);
        </script>
    </body>
</html>