carpool_news/carpool_news/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'carpool_news.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('rides.urls', namespace='rides')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^admin/', include(admin.site.urls)),
)

carpool_news/rides/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^$', 'rides.views.index', name='index'),
)

carpool_news/users/urls.py
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^login$', 'users.views.login', name='login'),
    url(r'^logout$', 'users.views.logout', name='logout'),
    url(r'^register$', 'users.views.register', name='register'),
    url(
        r'^routes$',
        'users.views.list_user_routes',
        name='list_user_routes'),
    url(
        r'^delete_user_route/(?P<id>\d+)$',
        'users.views.delete_user_route',
        name='delete_user_route'),
    url(
        r'^create_user_route$',
        'users.views.create_user_route',
        name='create_user_route')
)

carpool_news/users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from rides.models import Ride, Route
from arrow_field.model_fields import ArrowField


class UserRoute(models.Model):
    """
    Many-to-many mapping between users and routes
    with additional details of ad type
    """
    user = models.ForeignKey(User)
    route = models.ForeignKey(Route)

    # Type of route ads user is interested in
    is_looking_for = models.BooleanField(
        default=False,
        choices=((False, 'Siūlo'), (True, 'Ieško')))

    def get_current_rides(self):
        """
        Return rides which are:
        - Not yet expired
        - Not emailed to that user yet
        - Are of the defined type (is_looking_for)
        """
        rides = [
            ride for ride in self.route.rides.filter(
                is_expired=False,
                is_looking_for=self.is_looking_for)
            # Not emailed yet
            if not EmailedRide.objects.filter(
                user=self.user, ride=ride).exists()
        ]
        return rides


class EmailedRide(models.Model):
    """
    User and ride ad mapping for keeping track what was emailed to users
    """
    user = models.ForeignKey(User, related_name='emailed_rides')
    ride = models.ForeignKey(Ride, related_name='emailed_users')
    email_date = ArrowField()


def get_rides_to_email(user):
    """
    Find rides which are relevant to user
    and not yet emailed to him
    """
    rides = list(set([
        # Duplicates possible, as the same ride can belong to multiple routes
        ride
        for user_route in UserRoute.objects.filter(user=user)
        for ride in user_route.get_current_rides()
    ]))
    return rides

carpool_news/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from rides.models import Location, Route
from users.models import UserRoute


class UserForm(forms.ModelForm):
    password2 = forms.CharField(max_length=128)

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password2')

    def clean_password2(self):
        """
        Check if both passwords match
        """
        form_data = self.cleaned_data
        if form_data['password'] != form_data['password2']:
            self.add_error('password', "Passwords do not match")
        return form_data


class UserRouteForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        # Current user should be passed from the view (request.user)
        self.user = user
        super(UserRouteForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UserRoute
        fields = ['origin', 'destination', 'is_looking_for']
        widgets = {
            'is_looking_for': forms.RadioSelect()}
        labels = {
            'is_looking_for': 'Tipas'}

    origin = forms.ModelChoiceField(
        queryset=Location.objects.all().order_by('name'),
        label='Pradžia',
        required=True)
    destination = forms.ModelChoiceField(
        queryset=Location.objects.all().order_by('name'),
        label='Pabaiga',
        required=True)

    def clean(self):
        """
        Additional form validation
        """
        super(UserRouteForm, self).clean()

        # Selected origin and destination locations cannot match
        origin = self.cleaned_data['origin']
        destination = self.cleaned_data['destination']
        if origin == destination:
            raise ValidationError(u'Pradžia ir pabaiga negali sutapti')

        # User routes should be unique
        try:
            UserRoute.objects.get(
                user=self.user,
                route__origin=origin,
                route__destination=destination,
                is_looking_for=self.cleaned_data['is_looking_for'])
            raise ValidationError(u'Toks maršrutas jau pasirinktas')
        except UserRoute.DoesNotExist:
            pass

        return self.cleaned_data

    def save(self, commit=True):
        instance = super(UserRouteForm, self).save(commit=False)

        # Get route for specified origin/destination
        origin = self.cleaned_data['origin']
        destination = self.cleaned_data['destination']
        route, created = Route.objects.get_or_create(
            origin=origin,
            destination=destination)
        instance.route = route
        instance.user = self.user   # Set in constructor

        if commit:
            instance.save()
        return instance

carpool_news/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
import django.contrib.auth as auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from users.forms import UserForm, UserRouteForm
from users.models import UserRoute
from rides.models import Location


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            auth.login(request, user)
            # login_required decorator redirect
            if 'next' in request.POST and request.POST['next'] != '':
                return HttpResponseRedirect(request.POST['next'])
            else:
                return HttpResponseRedirect('/')
        else:
            return render(request, 'users/login.html', {
                'error_message': 'Login failed',
            })
    else:
        return render(request, 'users/login.html', {
            # login_required decorator redirect
            'next': request.GET['next'] if 'next' in request.GET else '',
        })


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # Login and redirect to root url
            user = auth.authenticate(
                username=request.POST['username'],
                password=request.POST['password'])
            auth.login(request, user)
            return HttpResponseRedirect('/')
    else:
        user_form = UserForm()

    return render(
        request,
        'users/register.html', {
            'form': user_form,
        })


@login_required
def list_user_routes(request):
    return _render_profile(request)


@login_required
def create_user_route(request):
    if request.method == 'POST':
        form = UserRouteForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('users:list_user_routes'))
        else:
            return _render_profile(request, form)


@login_required
def delete_user_route(request, id):
    user_route = get_object_or_404(
        UserRoute, user=request.user, id=id)
    if request.method == 'POST':
        user_route.delete()
    return redirect(reverse('users:list_user_routes'))


def _render_profile(request, form=None):
    cities = Location.objects.all()
    user_routes = UserRoute.objects.filter(user=request.user)
    if form is None:
        form = UserRouteForm(request.user)
    return render(request, 'users/profile.html', {
        'cities': cities,
        'user_routes': user_routes,
        'form': form,
    })

carpool_news/users/templates/users/email_lite.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>Your Message Subject or Title</title>
	<style type="text/css">
		/* Based on The MailChimp Reset INLINE: Yes. */  
		/* Client-specific Styles */
		#outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
		body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;} 
		/* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/ 
		.ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */  
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		/* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */ 
		#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
		/* End reset */

		/* Some sensible defaults for images
		Bring inline: Yes. */
		img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;} 
		a img {border:none;} 
		.image_fix {display:block;}

		/* Yahoo paragraph fix
		Bring inline: Yes. */
		p {margin: 1em 0;}

		/* Hotmail header color reset
		Bring inline: Yes. */
		h1, h2, h3, h4, h5, h6 {color: black !important;}

		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
		color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
		color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		/* Outlook 07, 10 Padding issue fix
		Bring inline: No.*/
		table td {border-collapse: collapse;}

		/* Remove spacing around Outlook 07, 10 tables
		Bring inline: Yes */
		table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }

		/* Styling your links has become much simpler with the new Yahoo.  In fact, it falls in line with the main credo of styling in email and make sure to bring your styles inline.  Your link colors will be uniform across clients when brought inline.
		Bring inline: Yes. */
		a {color: orange;}


		/***************************************************
		****************************************************
		MOBILE TARGETING
		****************************************************
		***************************************************/
		@media only screen and (max-device-width: 480px) {
			/* Part one of controlling phone number linking for mobile. */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}

		}

		/* More Specific Targeting */

		@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
		/* You guessed it, ipad (tablets, smaller screens, etc) */
			/* repeating for the ipad */
			a[href^="tel"], a[href^="sms"] {
						text-decoration: none;
						color: blue; /* or whatever your want */
						pointer-events: none;
						cursor: default;
					}

			.mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
						text-decoration: default;
						color: orange !important;
						pointer-events: auto;
						cursor: default;
					}
		}

		@media only screen and (-webkit-min-device-pixel-ratio: 2) {
		/* Put your iPhone 4g styles in here */ 
		}

		/* Android targeting */
		@media only screen and (-webkit-device-pixel-ratio:.75){
		/* Put CSS for low density (ldpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1){
		/* Put CSS for medium density (mdpi) Android layouts in here */
		}
		@media only screen and (-webkit-device-pixel-ratio:1.5){
		/* Put CSS for high density (hdpi) Android layouts in here */
		}
		/* end Android targeting */

	</style>

	<!-- Targeting Windows Mobile -->
	<!--[if IEMobile 7]>
	<style type="text/css">
	
	</style>
	<![endif]-->   

	<!-- ***********************************************
	****************************************************
	END MOBILE TARGETING
	****************************************************
	************************************************ -->

	<!--[if gte mso 9]>
		<style>
		/* Target Outlook 2007 and 2010 */
		</style>
	<![endif]-->
</head>
<body>
<!-- Wrapper/Container Table: Use a wrapper table to control the width and the background color consistently of your email. Use this approach instead of setting attributes on the body tag. -->
<table cellpadding="0" cellspacing="0" border="0" id="backgroundTable">
	<tr>
		<td valign="top"> 
		<!-- Tables are the most common way to format your email consistently. Set your table widths inside cells and in most cases reset cellpadding, cellspacing, and border to zero. Use nested tables as a way to space effectively in your message. -->
		<!-- <table cellpadding="0" cellspacing="0" border="0" align="center"> -->
			<!-- <tr> -->
				<!-- <td width="200" valign="top"></td> -->
				<!-- <td width="200" valign="top"></td> -->
				<!-- <td width="200" valign="top"></td> -->
			<!-- </tr> -->
		<!-- </table> -->
		<!-- End example table -->

		<h3>Sveiki, {{ user.username }}</h3>
		<p>Atsirado naujų pavežėjimo skelbimų, kurie Jus galėtų dominti:</p>

		<table cellpadding="10" cellspacing="10" border="1">
			{% for ride in rides %}
			<tr>
				<td>
					{{ ride.content }}<br>
					<a href="{{ ride.ad_url }}" target="_blank">
						{{ ride.ad_url }}
					</a>
				</td>
			</tr>
			{% endfor %}
		</table>

		<!-- Yahoo Link color fix updated: Simply bring your link styling inline. -->
		<!-- <a href="http://htmlemailboilerplate.com" target ="_blank" title="Styling Links" style="color: orange; text-decoration: none;">Coloring Links appropriately</a> -->

		<!-- Gmail/Hotmail image display fix -->
		<!-- <img class="image_fix" src="full path to image" alt="Your alt text" title="Your title text" width="x" height="x" /> -->

		<!-- Working with telephone numbers (including sms prompts).  Use the "mobile" class to style appropriately in desktop clients
		versus mobile clients. -->
		<!-- <span class="mobile_link">123-456-7890</span> -->

		<!-- </td> -->
	</tr>
</table>  
<!-- End of wrapper table -->
</body>
</html>

carpool_news/users/templates/users/login.html
{% extends 'base.html' %}

{% block navbar-class-login %}
active
{% endblock %}

{% block content %}
<div class="col-sm-6">
    <form action="{% url 'users:login' %}" method="POST" class="form-horizontal" role="form">
        {% csrf_token %}
        <legend>Prisijungimas</legend>
        <hr>

        <!-- Need to redirect somewhere after login? -->
        <input type="hidden" name="next" id="id_next" class="form-control" value="{{ next }}">

        <div class="form-group">
            <label for="id_username" 
                   class="col-sm-3 control-label">
                Vartotojo vardas:
            </label>
            <div class="col-sm-9">
                <input type="text" 
                       name="username" 
                       id="id_username" 
                       class="form-control" 
                       required="required" >
            </div>
        </div>

        <div class="form-group">
            <label for="id_password" 
                   class="col-sm-3 control-label">
                Slaptažodis:
            </label>
            <div class="col-sm-9">
                <input type="password" 
                       name="password" 
                       id="id_password" 
                       class="form-control" 
                       required="required" >
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <p>
                    {% if error_message %}
                    <span class="label label-danger">
                        {{ error_message }}
                    </span>
                    {% endif %}
                </p>
                <button type="submit" class="btn btn-primary">Prisijungti</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

carpool_news/users/templates/users/profile.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block navbar-class-user %}
active
{% endblock %}

{% block content %}
    <h3>{{ user.username }} ({{ user.email }})</h3>
    <hr>

    <div class="col-sm-6">
        <h4>Sekami maršrutai:</h4>
        {% if user_routes|length > 0 %}
            <ul class="list-group">
                {% for user_route in user_routes %}
                <li class="list-group-item">
                    <form action="{% url 'users:delete_user_route' user_route.id %}" method="POST" role="form">
                        {% csrf_token %}

                        {{ user_route.route.origin }}
                        &nbsp;
                        {% bootstrap_icon 'arrow-right' %}
                        &nbsp;
                        {{ user_route.route.destination }}
                        &nbsp;

                        {% if user_route.is_looking_for %}
                            <span class="label label-warning">
                                Ieško
                            </span>
                        {% else %}
                            <span class="label label-success">
                                Siūlo
                            </span>
                        {% endif %}

                        <button type="submit" class="btn btn-xs btn-danger pull-right">
                            {% bootstrap_icon 'remove' %}
                        </button>
                    </form>
                </li>
                {% endfor %}
            </ul>

        {% else %}
            Dar nėra. Pridėkite naują!
        {% endif %}
    </div>

    <div class="col-sm-6">
        <h4>Pridėti naują:</h4>
        <hr>
        <form action="{% url 'users:create_user_route' %}" method="POST" class="form-horizontal" role="form">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}

            {% buttons %}
                <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Pridėti</button>
                </div>
            {% endbuttons %}
        </form>
    </div>
{% endblock %}

carpool_news/users/templates/users/register.html
{% extends 'base.html' %}

{% block navbar-class-register %}
active
{% endblock %}

{% block content %}
<div class="col-sm-6">
    <form action="" method="POST" class="form-horizontal" role="form">
        {% csrf_token %}
        <legend>Registracija</legend>
        <hr>

        {% if form.subject.errors %}
        <ol>
            {% for error in form.subject.errors %}
            <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
        </ol>
        {% endif %}

        <div class="form-group">
            <label for="id_{{ form.username.name }}" 
                   class="col-sm-3 control-label">
                Vartotojo vardas:
            </label>
            <div class="col-sm-9">
                <input type="text" 
                       name="{{ form.username.name }}" 
                       id="id_{{ form.username.name }}" 
                       class="form-control" 
                       required="required"
                       value="{{ form.username.value|default_if_none:"" }}">
                {% for error in form.username.errors %}
                <span class="label label-danger">
                    {{ error }}
                </span>
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <label for="id_{{ form.email.name }}" 
                   class="col-sm-3 control-label">
                El. paštas:
            </label>
            <div class="col-sm-9">
                <input type="text" 
                       name="{{ form.email.name }}" 
                       id="id_{{ form.email.name }}" 
                       class="form-control" 
                       required="required"
                       value="{{ form.email.value|default_if_none:"" }}">
                {% for error in form.email.errors %}
                <span class="label label-danger">
                    {{ error }}
                </span>
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <label for="id_{{ form.password.name }}" 
                   class="col-sm-3 control-label">
                Slaptažodis:
            </label>
            <div class="col-sm-9">
                <input type="password" 
                       name="{{ form.password.name }}" 
                       id="id_{{ form.password.name }}" 
                       class="form-control" 
                       required="required" >
                {% for error in form.password.errors %}
                <span class="label label-danger">
                    {{ error }}
                </span>
                {% endfor %}
            </div>
        </div>

        <div class="form-group">
            <label for="id_{{ form.password2.name }}" 
                   class="col-sm-3 control-label">
                Pakartokite slaptažodį:
            </label>
            <div class="col-sm-9">
                <input type="password" 
                       name="{{ form.password2.name }}" 
                       id="id_{{ form.password2.name }}" 
                       class="form-control" 
                       required="required" >
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <button type="submit" class="btn btn-primary">Registruotis</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}